/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class Assign6Test {
    @Test public void appHasAGreeting() {
        Assign6 classUnderTest = new Assign6();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
